services:
  db:
    image: postgis/postgis:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: .
    user: "${UID}:${GID}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DB_HOST: postgres
      DB_NAME: inventory_db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata:
