# Generated by Django 5.1.3 on 2024-12-03 12:05

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import inventory.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('review_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='LocalizeAccommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[(inventory.enums.LanguageCode['ENGLISH'], 'en'), (inventory.enums.LanguageCode['FRENCH'], 'fr'), (inventory.enums.LanguageCode['SPANISH'], 'es'), (inventory.enums.LanguageCode['GERMAN'], 'de'), (inventory.enums.LanguageCode['ITALIAN'], 'it'), (inventory.enums.LanguageCode['PORTUGUESE'], 'pt'), (inventory.enums.LanguageCode['CHINESE'], 'zh'), (inventory.enums.LanguageCode['ARABIC'], 'ar'), (inventory.enums.LanguageCode['JAPANESE'], 'ja'), (inventory.enums.LanguageCode['RUSSIAN'], 'ru'), (inventory.enums.LanguageCode['BENGALI'], 'bn'), (inventory.enums.LanguageCode['HINDI'], 'hi'), (inventory.enums.LanguageCode['URDU'], 'ur'), (inventory.enums.LanguageCode['KOREAN'], 'ko'), (inventory.enums.LanguageCode['TURKISH'], 'tr'), (inventory.enums.LanguageCode['POLISH'], 'pl'), (inventory.enums.LanguageCode['DUTCH'], 'nl'), (inventory.enums.LanguageCode['SWEDISH'], 'sv'), (inventory.enums.LanguageCode['GREEK'], 'el'), (inventory.enums.LanguageCode['ROMANIAN'], 'ro'), (inventory.enums.LanguageCode['DANISH'], 'da'), (inventory.enums.LanguageCode['FINNISH'], 'fi'), (inventory.enums.LanguageCode['CZECH'], 'cs'), (inventory.enums.LanguageCode['HUNGARIAN'], 'hu'), (inventory.enums.LanguageCode['BULGARIAN'], 'bg'), (inventory.enums.LanguageCode['SLOVAK'], 'sk'), (inventory.enums.LanguageCode['SLOVENIAN'], 'sl'), (inventory.enums.LanguageCode['CROATIAN'], 'hr'), (inventory.enums.LanguageCode['SERBIAN'], 'sr'), (inventory.enums.LanguageCode['BOSNIAN'], 'bs'), (inventory.enums.LanguageCode['MACEDONIAN'], 'mk'), (inventory.enums.LanguageCode['LATVIAN'], 'lv'), (inventory.enums.LanguageCode['LITHUANIAN'], 'lt'), (inventory.enums.LanguageCode['ESTONIAN'], 'et'), (inventory.enums.LanguageCode['UKRAINIAN'], 'uk'), (inventory.enums.LanguageCode['BELARUSIAN'], 'be'), (inventory.enums.LanguageCode['GEORGIAN'], 'ka'), (inventory.enums.LanguageCode['ARMENIAN'], 'hy'), (inventory.enums.LanguageCode['PERSIAN'], 'fa'), (inventory.enums.LanguageCode['THAI'], 'th'), (inventory.enums.LanguageCode['VIETNAMESE'], 'vi'), (inventory.enums.LanguageCode['MALAY'], 'ms'), (inventory.enums.LanguageCode['INDONESIAN'], 'id'), (inventory.enums.LanguageCode['TAGALOG'], 'tl'), (inventory.enums.LanguageCode['SWAHILI'], 'sw'), (inventory.enums.LanguageCode['ZULU'], 'zu'), (inventory.enums.LanguageCode['AMHARIC'], 'am'), (inventory.enums.LanguageCode['SOMALI'], 'so'), (inventory.enums.LanguageCode['TAMIL'], 'ta'), (inventory.enums.LanguageCode['TELUGU'], 'te'), (inventory.enums.LanguageCode['KANNADA'], 'kn'), (inventory.enums.LanguageCode['MALAYALAM'], 'ml'), (inventory.enums.LanguageCode['SINHALESE'], 'si'), (inventory.enums.LanguageCode['BURMESE'], 'my'), (inventory.enums.LanguageCode['LAO'], 'lo'), (inventory.enums.LanguageCode['KHMERS'], 'km'), (inventory.enums.LanguageCode['TIBETAN'], 'bo'), (inventory.enums.LanguageCode['NEPALI'], 'ne'), (inventory.enums.LanguageCode['ICELANDIC'], 'is'), (inventory.enums.LanguageCode['NORWEGIAN'], 'no'), (inventory.enums.LanguageCode['HEBREW'], 'he'), (inventory.enums.LanguageCode['YIDDISH'], 'yi')], max_length=2)),
                ('description', models.TextField()),
                ('policy', models.JSONField(default=dict)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_type', models.CharField(choices=[(inventory.enums.LocationType['COUNTRY'], 'Country'), (inventory.enums.LocationType['STATE'], 'State'), (inventory.enums.LocationType['CITY'], 'City')], max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('state_abbr', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
    ]
