# Generated by Django 5.1.3 on 2024-12-04 04:03

import inventory.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_accommodation_images_delete_accommodationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[(inventory.enums.LocationType['COUNTRY'], 'country'), (inventory.enums.LocationType['STATE'], 'state'), (inventory.enums.LocationType['CITY'], 'city')], max_length=20),
        ),
    ]
