# Generated by Django 5.1.3 on 2024-12-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('COUNTRY', 'COUNTRY'), ('STATE', 'STATE'), ('CITY', 'CITY')], max_length=20),
        ),
    ]
