# Generated by Django 5.1.3 on 2024-12-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_partition_localize_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='language',
            field=models.CharField(choices=[('en', 'ENGLISH'), ('fr', 'FRENCH'), ('es', 'SPANISH'), ('de', 'GERMAN'), ('it', 'ITALIAN'), ('pt', 'PORTUGUESE'), ('zh', 'CHINESE'), ('ar', 'ARABIC'), ('ja', 'JAPANESE'), ('ru', 'RUSSIAN'), ('bn', 'BENGALI'), ('hi', 'HINDI'), ('ur', 'URDU'), ('ko', 'KOREAN'), ('tr', 'TURKISH'), ('pl', 'POLISH'), ('nl', 'DUTCH'), ('sv', 'SWEDISH'), ('el', 'GREEK'), ('ro', 'ROMANIAN'), ('da', 'DANISH'), ('fi', 'FINNISH'), ('cs', 'CZECH'), ('hu', 'HUNGARIAN'), ('bg', 'BULGARIAN'), ('sk', 'SLOVAK'), ('sl', 'SLOVENIAN'), ('hr', 'CROATIAN'), ('sr', 'SERBIAN'), ('bs', 'BOSNIAN'), ('mk', 'MACEDONIAN'), ('lv', 'LATVIAN'), ('lt', 'LITHUANIAN'), ('et', 'ESTONIAN'), ('uk', 'UKRAINIAN'), ('be', 'BELARUSIAN'), ('ka', 'GEORGIAN'), ('hy', 'ARMENIAN'), ('fa', 'PERSIAN'), ('th', 'THAI'), ('vi', 'VIETNAMESE'), ('ms', 'MALAY'), ('id', 'INDONESIAN'), ('tl', 'TAGALOG'), ('sw', 'SWAHILI'), ('zu', 'ZULU'), ('am', 'AMHARIC'), ('so', 'SOMALI'), ('ta', 'TAMIL'), ('te', 'TELUGU'), ('kn', 'KANNADA'), ('ml', 'MALAYALAM'), ('si', 'SINHALESE'), ('my', 'BURMESE'), ('lo', 'LAO'), ('km', 'KHMERS'), ('bo', 'TIBETAN'), ('ne', 'NEPALI'), ('is', 'ICELANDIC'), ('no', 'NORWEGIAN'), ('he', 'HEBREW'), ('yi', 'YIDDISH')], max_length=2),
        ),
    ]
