# Generated by Django 5.1.3 on 2024-12-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_localizeaccommodation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='location_id',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.accommodation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location'),
        ),
    ]
